version: '3'

services:
  node:
    image: node:lts-alpine
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    expose:
      - 8080:8080
    command: npm run dev
    restart: always

  db:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    expose:
      - 3306:3306
    restart: always