version: '3'

services:
  node:
    build: ./
    env_file:
      - .env
    working_dir: /app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      notes-db:
        condition: service_healthy

  notes-db:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - notes-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    restart: always

volumes:
  notes-data:
